entries:
  - client:
      repositories:
        - /^civitaspo\/.+$/
      branches:
        - main
        - /^.*$/
    push:
      repositories:
        - /^civitaspo\/.+$/
      branches:
        - /^.*$/
