name: Approve Pull Request
run-name: Approve Pull Request (${{ github.event.label.name }})

on:
  label:
    types:
      - created

permissions: {}

concurrency:
  group: approve-${{ github.event.label.name }}
  cancel-in-progress: false

jobs:
  approve:
    if: startsWith(github.event.label.name, 'approve-pr-')
    name: Approve Pull Request (${{ github.event.label.description }})
    runs-on: ubuntu-latest
    environment: main
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Approve pull request
        uses: csm-actions/approve-pr-action@a8fdc60ab4d9b446694140534bbcc71c29fb499c # v1.0.0
        with:
          github_token: ${{ secrets.CIVITASPO_BOT_PR_APPROVE_TOKEN }}
          app_id: ${{ vars.SECUREFIX_SERVER_APP_ID }}
          app_private_key: ${{ secrets.SECUREFIX_SERVER_PRIVATE_KEY }}
          allowed_committers: |
            civitaspo
            cursoragent
            civitaspo-securefix-server[bot]
            renovate[bot]
            dependabot[bot]
