name: Approve Request

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  issue_comment:
    types:
      - created

permissions: {}

concurrency:
  group: approve-request-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  request:
    uses: ./.github/workflows/reusable-approve-request.yml
    permissions:
      contents: read
      issues: read
      pull-requests: read
    secrets: inherit
