name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflows:
    name: GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Run actionlint
        run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12 -shellcheck=
